services:
  mongodb:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: shrinker-db
    restart: always
    env_file:
      - .env
    ports:
      - '${DB_PORT}:27017'
    volumes:
      - mongo-data:/data/db
  redis:
    container_name: shrinker-redis
    restart: always
    env_file:
      - .env
    image: redis/redis-stack-server
    ports:
      - '${REDIS_PORT}:6379'

volumes:
  mongo-data:
